language: scala
scala:
- 2.11.8
script: sbt clean test
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
notifications:
  email:
    recipients:
    - kinjacono@yahoo.co.uk

