package duesoldi.dependencies

import duesoldi.blog.dependencies.BlogDependencies
import duesoldi.debug.dependencies.AppDebugDependencies
import duesoldi.gallery.GalleryDependencies
import duesoldi.metrics.dependencies.AccessRecordingDependencies

object DueSoldiDependencies
extends GalleryDependencies
with BlogDependencies
with AccessRecordingDependencies
with AppDebugDependencies
